resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: vstest

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.402'
  inputs:
    version: 2.1.402


- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'


- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

    projects: '$(buildProjects)'


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(buildProjects)'

    arguments: '--configuration $(BuildConfiguration)'


- task: VSTest@2
  displayName: 'Integration tests'
  inputs:
    testAssemblyVer2: |
     **\*Integration.Test*.dll
     !**\*TestAdapter.dll
     !**\obj\**

    otherConsoleOptions: '/Framework:".NETCoreApp,Version=v2.1" /Blame '

    platform: '$(BuildPlatform)'

    configuration: '$(BuildConfiguration)'

    rerunFailedTests: true


- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish

    publishWebProjects: True

    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    zipAfterPublish: True


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'



